[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cost-analysis-regression"
version = "0.1.0"
description = "Regression-based cost forecasting from SMAPI events data"
requires-python = ">=3.10"
dependencies = [
    "kaggle",
    "ipykernel",
    "python-dotenv",
    "pandas",
    "pyarrow",
    "matplotlib"
]

[tool.setuptools.packages.find]
where = ["src"]
